[build]
  publish = "build/web"
  command = "git clone https://github.com/flutter/flutter.git --depth 1 -b stable /tmp/flutter && export PATH=$PATH:/tmp/flutter/bin && flutter config --enable-web && flutter build web --release"

[build.environment]
  # Memaksa Netlify mengabaikan pemasangan Ruby/Bundler
  NETLIFY_SKIP_RUBY_INSTALL = "1"
  # Menetapkan versi Node yang stabil
  NODE_VERSION = "20"
