[build]
  publish = "build/web"
  command = "rm -rf flutter && git clone https://github.com/flutter/flutter.git -b stable --depth 1 && ./flutter/bin/flutter build web --release"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
