[build]
  publish = "build/web"
  command = "git clone https://github.com/flutter/flutter.git --depth 1 -b stable $FLUTTER_HOME && $FLUTTER_HOME/bin/flutter build web --release"

[build.environment]
  FLUTTER_HOME = "/opt/build/cache/flutter"
  PATH = "/opt/build/cache/flutter/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
